language: swift
osx_image: xcode11.2
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=BezierKit/BezierKit.xcodeproj
  - IOS_SCHEME=BezierKit_iOS
  - IOS_SDK=iphonesimulator13.2
  - OSX_SCHEME=BezierKit_Mac
  - OSX_SDK=macosx10.15
  matrix:
    - DESTINATION="OS=10.3.1,name=iPhone 5" SCHEME="$IOS_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" POD_LINT="NO"
    - DESTINATION="OS=13.2.2,name=iPad Pro (12.9-inch) (3rd generation)" SCHEME="$IOS_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" POD_LINT="NO"
    - DESTINATION="arch=x86_64"SCHEME="$OSX_SCHEME"     SDK="$OSX_SDK"     RUN_TESTS="YES" POD_LINT="NO"
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c;
    else
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi

  # Run `pod spec lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      pod spec lint;
    fi

after_success:
   - bash <(curl -s https://codecov.io/bash)
   - sleep 5
